CREATE OR REPLACE VIEW DM.V_EVENTS AS 
WITH
Q11 AS
(
SELECT
EVENTS_KEY  AS  EVENTS_KEY
 ,ACT_DT   AS   ACT_DT
 ,ADVANCE_PERCENT  AS   ADVANCE_PERCENT
 ,AGENT_FEE_AMT  AS   AGENT_FEE_AMT
 ,AGENT_FEE_RATE   AS   AGENT_FEE_RATE
 ,AGREEMENT_RESULT   AS   AGREEMENT_RESULT
 ,APPEAL_SOURCE  AS   APPEAL_SOURCE
 ,APPROVAL_CONDITIONS AS   APPROVAL_CONDITIONS
 ,APPROVAL_RESULT  AS   APPROVAL_RESULT
 ,APPROVAL_ROUTE   AS   APPROVAL_ROUTE
 ,BREND_MODEL_NAM  AS   BREND_MODEL_NAM
 ,BREND_NAM  AS   BREND_NAM
 ,BUSINESS_UNIT_NAM  AS   BUSINESS_UNIT_NAM
 ,CAR_TYPE_NAM   AS   CAR_TYPE_NAM
 ,COMISSION_AMT  AS   COMISSION_AMT
 ,COMISSION_RATE  AS   COMISSION_RATE
 ,CONVERT_RATE   AS   CONVERT_RATE
 ,COUNTRY_RU_NAM  AS   COUNTRY_RU_NAM
 ,CRM_CONTRACT_ID_CD AS   CRM_CONTRACT_ID_CD
 ,CRM_SUBJECT_CD  AS   CRM_SUBJECT_CD
 ,CURRENCY_LEAS_SUBJECT AS   CURRENCY_LEAS_SUBJECT
 ,EVENT  AS   EVENT
,EVENT_DATE  AS  EVENT_DATE
 ,EVENT_NUM  AS   EVENT_NUM
 ,FINANCE_AMT  AS   FINANCE_AMT
 ,FULLCOST_AMT   AS   FULLCOST_AMT
 ,INN_LEASEHOLDER  AS   INN_LEASEHOLDER
 ,INN_SUPPLIER AS   INN_SUPPLIER
 ,KASKO_CRM_CLIENT_NAM   AS   KASKO_CRM_CLIENT_NAM
 ,LEASE_TERM   AS   LEASE_TERM
 ,LEASING_SUBJECT_NAM  AS   LEASING_SUBJECT_NAM
 ,LEASING_SUBJECT_NUM  AS   LEASING_SUBJECT_NUM
 ,LIQUIDITY_GROUP  AS   LIQUIDITY_GROUP
 ,MANAGER_NAM  AS   MANAGER_NAM
 ,MODEL_NAM  AS   MODEL_NAM
 ,NAM_LEASEHOLDER  AS   NAM_LEASEHOLDER
 ,OFFER_RATE   AS   OFFER_RATE
 ,OKVED_CODE   AS   OKVED_CODE
 ,PAYMENT_TYPE_NAM   AS   PAYMENT_TYPE_NAM
 ,PLAN_AMT   AS   PLAN_AMT
 ,PREPAY_AMT   AS   PREPAY_AMT
 ,PREPAY_RATE  AS   PREPAY_RATE
 ,PRE_CONTRACT_ID_CD AS   PRE_CONTRACT_ID_CD
 ,PRE_CONTRACT_NUM   AS   PRE_CONTRACT_NUM
 ,PRODUCT_NAM  AS   PRODUCT_NAM
 ,RECOMMENDAT_DESC AS   RECOMMENDAT_DESC
 ,REDEMPTION_AMT   AS   REDEMPTION_AMT
 ,REDUCE_STEP  AS   REDUCE_STEP
 ,REHIRING_FLG AS   REHIRING_FLG
 ,CASE
WHEN EVENT_NUM=10000001 THEN 'Запуск задачи на верификацию'
  WHEN EVENT_NUM=10000002 THEN 'Запуск задачи на Экпертизу УОБ'
    WHEN EVENT_NUM=10000003 THEN 'Закрыте экспертизы УОБ'
      WHEN EVENT_NUM=10000004 THEN 'Закрытие экспертизы УАиКР'
        WHEN EVENT_NUM=10000005 THEN 'Запуск задачи на Одобрение'
          WHEN EVENT_NUM=10000006 THEN 'Закрытие задачи Одобрения'
                      WHEN EVENT_NUM=10000007 THEN 'Запуск задачи подготовки договоров'
                                  WHEN EVENT_NUM=10000008 THEN 'Закрытие подготовки договоров'
                                              WHEN EVENT_NUM=10000009 THEN 'Подписание договоров'
                      WHEN EVENT_NUM=10000010 THEN 'Передача в лизинг'
                        end   AS   STAGE
 ,SUBPRODUCT_NAM   AS   SUBPRODUCT_NAM
 ,SUBSIDY_AMT  AS   SUBSIDY_AMT
 ,SUBSIDY_FLG  AS   SUBSIDY_FLG
 ,SUBSIDY_PROGRAM  AS   SUBSIDY_PROGRAM
 ,SUBSIDY_SHARE  AS   SUBSIDY_SHARE
 ,SUPPLIER_NAM AS   SUPPLIER_NAM
 ,TASK_HISTORY AS   TASK_HISTORY
 ,TASK_SUBJECT AS   TASK_SUBJECT
 ,TESTDRIVE_FLG  AS   TESTDRIVE_FLG
 ,USED_FLG AS   USED_FLG
 ,VEHICLE_CATEGORY_NAM AS   VEHICLE_CATEGORY_NAM
 ,FILE_ID  AS   FILE_ID
 ,SESS_NO  AS   SESS_NO
 ,VALID_FROM_DTTM  AS   VALID_FROM_DTTM
 ,VALID_TO_DTTM  AS   VALID_TO_DTTM
 ,PROCESS_KEY  AS   PROCESS_KEY
 ,W_RATE AS   W_RATE
 ,W_ADVANCE  AS   W_ADVANCE
 ,W_AGENT_FEE_AMT  AS   W_AGENT_FEE_AMT
 ,W_COMMISSION_AMT AS   W_COMMISSION_AMT
 ,W_LEASE_TERM AS   W_LEASE_TERM
 ,W_REDUCE_STEP  AS   W_REDUCE_STEP
  FROM DWH.EVENTS
)
,
Q1 AS
(
SELECT A.EVENT_DATE AS EVENT_DATE, A.STAGE AS STAGE, B.EVENT AS EVENT,A.EVENTS_KEY AS EVENTS_KEY FROM
(SELECT MIN(Q11.EVENT_DATE) AS EVENT_DATE, Q11.STAGE AS STAGE,Q11.EVENTS_KEY AS EVENTS_KEY FROM Q11
where Q11.STAGE IN ('Запуск задачи на верификацию','Запуск задачи на Экспертизу УОБ','Запуск задачи на Одобрение'
,'Запуск задачи подготовки договоров','Закрытие подготовки договоров','Подписание договоров','Передача в лизинг')
GROUP BY Q11.STAGE,Q11.EVENTS_KEY)A
INNER JOIN  (SELECT Q11.STAGE AS STAGE, Q11.EVENT_DATE AS EVENT_DATE,Q11.EVENT
,Q11.EVENTS_KEY AS EVENTS_KEY  FROM Q11) B
ON
A.STAGE=B.STAGE AND
A.EVENT_DATE=B.EVENT_DATE AND
A.EVENTS_KEY=B.EVENTS_KEY
)
,
Q2 AS
(
SELECT A.EVENT_DATE AS EVENT_DATE, A.STAGE AS STAGE, B.EVENT AS EVENT,A.EVENTS_KEY AS EVENTS_KEY FROM
(SELECT MAX(Q11.EVENT_DATE) AS EVENT_DATE, Q11.STAGE AS STAGE,Q11.EVENTS_KEY AS EVENTS_KEY FROM Q11
where Q11.STAGE IN ('Закрытие задачи Одобрения','Закрытие экспертизы УОБ','Закрытие экспертизы УАиКР'
)
GROUP BY Q11.STAGE, Q11.EVENTS_KEY
)A
INNER JOIN  (SELECT Q11.STAGE AS STAGE, Q11.EVENT_DATE AS EVENT_DATE
,Q11.EVENT AS EVENT, Q11.EVENTS_KEY AS EVENTS_KEY FROM Q11) B
ON
A.STAGE=B.STAGE AND
A.EVENT_DATE=B.EVENT_DATE AND
A.EVENTS_KEY=B.EVENTS_KEY
)
,
Q3 AS
(SELECT Q11.events_key AS EVENTS_KEY
,Q11.act_dt AS ACT_DT
,Q11.advance_percent AS ADVANCE_PERCENT
,Q11.agent_fee_amt AS AGENT_FREE_AMT
,Q11.agent_fee_rate AS AGENT_FREE_RATE
,Q11.agreement_result AS AGREEMENT_RESULT
,Q11.appeal_source AS APPEAL_SOURCE
,Q11.approval_conditions AS APPROVAL_CONDITIONS
,Q11.approval_result AS APPROVAL_RESULT
,Q11.approval_route AS APPROVAL_ROUTE
,Q11.brend_model_nam AS BREND_MODEL_NAM
,Q11.brend_nam AS BREND_NAM
,Q11.business_unit_nam AS BUSINESS_UNIT_NAM
,Q11.car_type_nam AS CAR_TYPE_NAM
,Q11.comission_amt AS COMISSION_AMT
,Q11.comission_rate AS COMISSION_RATE
,Q11.convert_rate AS CONVERT_RATE
,Q11.country_ru_nam AS COUNTRY_RU_NAM
,Q11.crm_contract_id_cd AS CRM_CONTRACT_ID_CD
,Q11.crm_subject_cd AS CRM_SUBJECT_CD
,Q11.currency_leas_subject AS CURRENCY_LEAS_SUBJECT
,Q1.event AS EVENT
,Q1.event_date AS EVENT_DATE
,Q11.event_num AS EVENT_NUM
,Q11.finance_amt AS FINANCE_AMT
,Q11.fullcost_amt AS FULLCOST_AMT
,Q11.inn_leaseholder AS INN_LEASEHOLDER
,Q11.inn_supplier AS INN_SUPPLIER
,Q11.kasko_crm_client_nam AS kasko_crm_client_nam
,Q11.lease_term AS LEASE_TERM
,Q11.leasing_subject_nam AS LEASING_SUBJECT_NAM
,Q11.leasing_subject_num AS LEASING_SUBJECT_NUM
,Q11.liquidity_group AS LIQUIDITY_GROUP
,Q11.manager_nam AS MANAGER_NAM
,Q11.model_nam AS MODEL_NAM
,Q11.nam_leaseholder AS NAM_LEASEHOLDER
,Q11.offer_rate AS OFFER_RATE
,Q11.okved_code AS OKVED_CODE
,Q11.payment_type_nam AS PAYMENT_TYPE_NAM
,Q11.plan_amt AS PLAN_AMT
,Q11.prepay_amt AS PREPAY_AMT
,Q11.prepay_rate AS PREPAY_RATE
,Q11.pre_contract_id_cd AS PRE_CONTRACT_ID_CD
,Q11.pre_contract_num AS PRE_CONTRACT_NUM
,Q11.product_nam AS PRODUCT_NAM
,Q11.recommendat_desc AS RECOMMENDAT_DESC
,Q11.redemption_amt AS REDEMPTION_AMT
,Q11.reduce_step AS REDUCE_STEP
,Q11.rehiring_flg AS REHIRING_FLG
,Q1.stage AS STAGE
,Q11.subproduct_nam AS SUBPRODUCT_NAM
,Q11.subsidy_amt AS SUBSIDY_AMT
,Q11.subsidy_flg AS SUBSIDY_FLG
,Q11.subsidy_program AS SUBSIDY_PROGRAM
,Q11.subsidy_share AS SUBSIDY_SHARE
,Q11.supplier_nam AS SUPPLIER_NAM
,Q11.task_history AS TASK_HISTORY
,Q11.task_subject AS TASK_SUBJECT
,Q11.testdrive_flg AS TESTDRIVE_FLG
,Q11.used_flg AS USED_FLG
,Q11.vehicle_category_nam AS VEHICLE_CATEGORY_NAM
,Q11.file_id AS FILE_ID
,Q11.sess_no AS SESS_NO
,Q11.valid_from_dttm AS VALID_FROM_DTTM
,Q11.valid_to_dttm AS VALID_TO_DTTM
,Q11.process_key AS PROCESS_KEY
,Q11.w_rate AS W_RATE
,Q11.w_advance AS W_ADVANCE
,Q11.w_agent_fee_amt AS W_AGENT_FREE_AMT
,Q11.w_commission_amt AS W_COMMISSION_AMT
,Q11.w_lease_term AS W_LEASE_TERM
,Q11.w_reduce_step AS W_REDUCE_STEP
 FROM Q11 INNER JOIN Q1
 ON
 Q1.STAGE=Q11.STAGE AND
 Q1.EVENT_DATE=Q11.EVENT_DATE AND
 Q1.EVENT=Q11.EVENT AND
 Q1.EVENTS_KEY=Q11.EVENTS_KEY
),
Q4 AS
(SELECT Q11.events_key AS EVENTS_KEY
,Q11.act_dt AS ACT_DT
,Q11.advance_percent AS ADVANCE_PERCENT
,Q11.agent_fee_amt AS AGENT_FREE_AMT
,Q11.agent_fee_rate AS AGENT_FREE_RATE
,Q11.agreement_result AS AGREEMENT_RESULT
,Q11.appeal_source AS APPEAL_SOURCE
,Q11.approval_conditions AS APPROVAL_CONDITIONS
,Q11.approval_result AS APPROVAL_RESULT
,Q11.approval_route AS APPROVAL_ROUTE
,Q11.brend_model_nam AS BREND_MODEL_NAM
,Q11.brend_nam AS BREND_NAM
,Q11.business_unit_nam AS BUSINESS_UNIT_NAM
,Q11.car_type_nam AS CAR_TYPE_NAM
,Q11.comission_amt AS COMISSION_AMT
,Q11.comission_rate AS COMISSION_RATE
,Q11.convert_rate AS CONVERT_RATE
,Q11.country_ru_nam AS COUNTRY_RU_NAM
,Q11.crm_contract_id_cd AS CRM_CONTRACT_ID_CD
,Q11.crm_subject_cd AS CRM_SUBJECT_CD
,Q11.currency_leas_subject AS CURRENCY_LEAS_SUBJECT
,Q2.event AS EVENT
,Q2.event_date AS EVENT_DATE
,Q11.event_num AS EVENT_NUM
,Q11.finance_amt AS FINANCE_AMT
,Q11.fullcost_amt AS FULLCOST_AMT
,Q11.inn_leaseholder AS INN_LEASEOLDER
,Q11.inn_supplier AS INN_SUPPLIER
,Q11.kasko_crm_client_nam AS KASKO_CRM_CLIENT_NAM
,Q11.lease_term AS LEASE_TERM
,Q11.leasing_subject_nam AS LEASING_SUBJECT_NAM
,Q11.leasing_subject_num AS LEASING_SUBJECT_NUM
,Q11.liquidity_group AS LIQUIDITY_GROUP
,Q11.manager_nam AS MANAGER_NAM
,Q11.model_nam AS MODEL_NAM
,Q11.nam_leaseholder AS NAM_LEASEHOLDER
,Q11.offer_rate AS OFFER_RATE
,Q11.okved_code AS OKVED_CODE
,Q11.payment_type_nam AS PAYMENT_TYPE_NAM
,Q11.plan_amt AS PLAN_AMT
,Q11.prepay_amt AS PREPAY_AMT
,Q11.prepay_rate AS PREPAY_RATE
,Q11.pre_contract_id_cd AS PRE_CONTRACT_ID_CD
,Q11.pre_contract_num AS PRE_CONTRACT_NUM
,Q11.product_nam AS PRODUCT_NAM
,Q11.recommendat_desc AS RECOMMENDAT_DESC
,Q11.redemption_amt AS REDEMPTION_AMT
,Q11.reduce_step AS REDUCE_STEP
,Q11.rehiring_flg AS REHIRING_FLG
,Q2.stage AS STAGE
,Q11.subproduct_nam AS SUBPRODUCT_NAM
,Q11.subsidy_amt AS SUBSIDY_AMT
,Q11.subsidy_flg AS SUBSIDY_FLG
,Q11.subsidy_program AS SUBSIDY_PROGRAM
,Q11.subsidy_share AS SUBSIDY_SHARE
,Q11.supplier_nam AS SUPPLIER_NAM
,Q11.task_history AS TASK_HISTORY
,Q11.task_subject AS TASK_SUBJECT
,Q11.testdrive_flg AS TESTDRIVE_FLG
,Q11.used_flg AS USED_FLG
,Q11.vehicle_category_nam AS VEHICLE_CATEGORY_NAM
,Q11.file_id AS FILE_ID
,Q11.sess_no AS SESS_NO
,Q11.valid_from_dttm AS VALID_FROM_DTTM
,Q11.valid_to_dttm AS VALID_TO_DTTM
,Q11.process_key AS PROCESS_KEY
,Q11.w_rate AS W_RATE
,Q11.w_advance AS W_ADVANCE
,Q11.w_agent_fee_amt AS W_AGENT_FREE_AMT
,Q11.w_commission_amt AS W_COMMISSION_AMT
,Q11.w_lease_term AS W_LEASE_TERM
,Q11.w_reduce_step AS W_REDUCE_STEP
 FROM Q11 INNER JOIN Q2
 ON
 Q2.STAGE=Q11.STAGE AND
 Q2.EVENT_DATE=Q11.EVENT_DATE AND
 Q2.EVENT=Q11.EVENT AND
 Q2.EVENTS_KEY=Q11.EVENTS_KEY
)
SELECT * FROM Q3
UNION ALL
SELECT * FROM Q4;