CREATE OR REPLACE VIEW STG_XML_CRM.V_CRM_EVENTS AS
SELECT le.events_key,
       la.agreement_key,
       TO_DATE(c.ACT_DT, 'yyyy-mm-dd hh24:mi:ss') ACT_DT,
       TO_DATE(c.TASK_BEGIN_DT, 'yyyy-mm-dd hh24:mi:ss') TASK_BEGIN_DT,
       TO_DATE(c.TASK_END_DT, 'yyyy-mm-dd hh24:mi:ss') TASK_END_DT,
       c.ADVANCE_PERCENT,
       c.advpayment,
       c.AGENT_FEE_AMT,
       c.AGENT_FEE_RATE/100 AGENT_FEE_RATE,
       c.AGREEMENT_RESULT,
       c.APPEAL_SOURCE,
       c.APPROVAL_CONDITIONS,
       c.APPROVAL_RESULT,
       c.APPROVAL_ROUTE,
       c.BREND_MODEL_NAM,
       c.BREND_NAM,
       c.BUSINESS_UNIT_NAM,
       c.CAR_TYPE_NAM,
       c.COMISSION_AMT,
       c.COMISSION_RATE/100 COMISSION_RATE,
       c.CONVERT_RATE,
       c.COUNTRY_RU_NAM,
       c.CRM_CONTRACT_ID_CD,
       c.CRM_SUBJECT_CD,
       c.CURRENCY_LEAS_SUBJECT,
       c.EVENT,
       TO_DATE(c.EVENT_DATE, 'yyyy-mm-dd hh24:mi:ss') EVENT_DATE,
       c.EVENT_NUM,
       c.FINANCE_AMT,
       c.FULLCOST_AMT,
       c.INN_LEASEHOLDER,
       c.INN_SUPPLIER,
       c.KASKO_CRM_CLIENT_NAM,
       c.LEASE_TERM,
       c.LEASING_SUBJECT_NAM,
       c.LEASING_SUBJECT_NUM,
       c.LIQUIDITY_GROUP,
       c.MANAGER_NAM,
       c.MODEL_NAM,
       c.NAM_LEASEHOLDER,
       c.OFFER_RATE/100 OFFER_RATE,
       c.OKVED_CODE,
       c.PAYMENT_TYPE_NAM,
       c.PLAN_AMT,
       CASE WHEN c.SUBSIDY_FLG=0 THEN PREPAY_AMT  
            WHEN c.SUBSIDY_FLG=1 THEN ADVPAYMENT END PREPAY_AMT,
       CASE WHEN c.SUBSIDY_FLG=0 THEN c.PREPAY_RATE/100,
            WHEN c.SUBSIDY_FLG=1 THEN c.PREPAY_RATE/100 END PREPAY_RATE,
       c.PRE_CONTRACT_ID_CD,
       c.PRE_CONTRACT_NUM,
       c.PRODUCT_NAM,
       c.RECOMMENDAT_DESC,
       c.REDEMPTION_AMT,
       c.REDUCE_STEP,
       c.REHIRING_FLG,
       c.STAGE,
       c.SUBPRODUCT_NAM,
       c.SUBSIDY_AMT,
       c.SUBSIDY_FLG,
       c.SUBSIDY_PROGRAM,
       c.SUBSIDY_SHARE,
       c.SUPPLIER_NAM,
       c.TASK_HISTORY,
       c.TASK_SUBJECT,
       c.TESTDRIVE_FLG,
       c.USED_FLG,
       c.VEHICLE_CATEGORY_NAM,
       c.FILE_ID,
       c.SESS_NO
/*, to_number(OFFER_RATE) * to_number(CONVERT_RATE) *
(to_number(FULLCOST_AMT) - to_number(PREPAY_AMT)) W_RATE,
PREPAY_RATE * FULLCOST_AMT * CONVERT_RATE W_ADVANCE,
FULLCOST_AMT * AGENT_FEE_RATE * CONVERT_RATE W_AGENT_FEE_AMT,
FINANCE_AMT * COMISSION_RATE * CONVERT_RATE - PREPAY_AMT W_COMMISSION_AMT,
FINANCE_AMT * LEASE_TERM * CONVERT_RATE - PREPAY_AMT W_LEASE_TERM,
(FINANCE_AMT * REDUCE_STEP * CONVERT_RATE - PREPAY_AMT) W_REDUCE_STEP*/
  FROM stg_xml_crm.crm_events c
  LEFT JOIN lnk.LNK_EVENTS le
    ON c.LEASING_SUBJECT_NUM = le.LEASING_SUBJECT_NUM_1
   and c.crm_contract_id_cd = le.crm_contract_id_cd_1
   and TO_DATE(c.EVENT_DATE, 'yyyy-mm-dd hh24:mi:ss') = le.date_1
  LEFT JOIN lnk.lnk_agreements la
    on la.AGREEMENT_CD_1 = agreement_result;
