CREATE OR REPLACE FORCE VIEW STG_XML_CRM.V_CRM_EVENTS AS
SELECT le.events_key,
       c.* /*,
       to_number(OFFER_RATE) * to_number(CONVERT_RATE) *
       (to_number(FULLCOST_AMT) - to_number(PREPAY_AMT)) W_RATE,
       PREPAY_RATE * FULLCOST_AMT * CONVERT_RATE W_ADVANCE,
       FULLCOST_AMT * AGENT_FEE_RATE * CONVERT_RATE W_AGENT_FEE_AMT,
       FINANCE_AMT * COMISSION_RATE * CONVERT_RATE - PREPAY_AMT W_COMMISSION_AMT,
       FINANCE_AMT * LEASE_TERM * CONVERT_RATE - PREPAY_AMT W_LEASE_TERM,
       (FINANCE_AMT * REDUCE_STEP * CONVERT_RATE - PREPAY_AMT) W_REDUCE_STEP*/
  FROM stg_xml_crm.crm_events c
  LEFT JOIN lnk.LNK_EVENTS le
    ON c.LEASING_SUBJECT_NUM = le.LEASING_SUBJECT_NUM_1
   and c.Task_Begin_Dt = le.leasing_subject_num_1

